global:
  resolve_timeout: 1m

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 4h
  receiver: 'webhook_receiver'
  routes: []

receivers:
- name: 'webhook_receiver'
  webhook_configs:
  - url: 'http://host.docker.internal:5000/alert'
    send_resolved: true
