global:
  scrape_interval: 10s
  evaluation_interval: 30s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093' # Replace with the Alertmanager's IP or hostname, and port if different

rule_files:
  - alert.rules.yml


scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']
- job_name: 'blackbox'
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - http://host.docker.internal:1234/metrics
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115
- job_name: 'cpu_metrics'
  static_configs:
  - targets: ['host.docker.internal:1234']
  metrics_path: /metrics
